#!/usr/bin/env python3
"""Capture CLI evidence — run all registered cases and generate Markdown docs.

Usage:
    python scripts/capture_cli_evidence.py           # offline + mocked (default)
    python scripts/capture_cli_evidence.py --live     # also run category-B against real backend
    python scripts/capture_cli_evidence.py --command create  # single command group
"""
from __future__ import annotations

import argparse
import os
import sys
from collections import defaultdict
from pathlib import Path

# Ensure project root is on sys.path
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from click.testing import CliRunner  # noqa: E402

from scripts.evidence_cases import REGISTRY, EvidenceCase, normalize  # noqa: E402
from serverless_sandbox.cli.main import cli  # noqa: E402
from serverless_sandbox.transport.config import reset_config  # noqa: E402

_GENERATED_HEADER = (
    "<!-- ⚠️  AUTO-GENERATED by scripts/capture_cli_evidence.py — DO NOT EDIT -->\n\n"
)


# ─── runner ────────────────────────────────────────────────────────────────


def run_case(case: EvidenceCase, runner: CliRunner) -> tuple[str, str, int]:
    """Execute a single evidence case and return (stdout, stderr, exit_code)."""
    reset_config()
    cmd = list(case.command)
    if case.mock_setup is not None:
        with case.mock_setup() as env:
            if "command" in env:
                cmd = env["command"]
            result = runner.invoke(cli, cmd)
    else:
        result = runner.invoke(cli, cmd)
    return result.output or "", result.stderr or "", result.exit_code


# ─── markdown helpers ──────────────────────────────────────────────────────


def _cmd_display(cmd: list[str]) -> str:
    """Pretty-print a command list for Markdown fenced block."""
    parts: list[str] = []
    for c in cmd:
        if " " in c or any(ch in c for ch in "'\""):
            parts.append(f'"{c}"')
        else:
            parts.append(c)
    return "sbox " + " ".join(parts)


def case_to_markdown(
    case: EvidenceCase, stdout: str, stderr: str, exit_code: int
) -> str:
    lines = [f"### {case.description}\n"]
    lines.append("```")
    lines.append(f"$ {_cmd_display(case.command)}")
    if stdout.strip():
        lines.append(stdout.rstrip())
    lines.append(f"Exit code: {exit_code}")
    lines.append("```")
    if stderr.strip():
        lines.append("\n**stderr:**\n")
        lines.append("```")
        lines.append(stderr.rstrip())
        lines.append("```")
    lines.append("")
    return "\n".join(lines)


def _group_key(output_file: str) -> str:
    """Derive a doc-group key from the output_file name."""
    return output_file.split("-")[0]


# ─── main ──────────────────────────────────────────────────────────────────


_DOC_SUBDIR_MAP = {
    "config": "cli/config",
    "template": "cli/template",
    "mcp": "cli/mcp",
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Capture CLI evidence")
    parser.add_argument(
        "--live",
        action="store_true",
        help="Run category-B cases against real backend (requires E2B_API_KEY)",
    )
    parser.add_argument("--command", type=str, default=None, help="Run only cases matching this prefix")
    args = parser.parse_args()

    live_available = bool(os.environ.get("E2B_API_KEY"))
    runner = CliRunner()

    groups: dict[str, list[str]] = defaultdict(list)
    total, skipped = 0, 0

    for case in REGISTRY:
        if args.command and not case.output_file.startswith(args.command):
            continue
        total += 1

        # Decide whether to run this case
        if case.category == "B" and case.mock_setup is None:
            if not (args.live and live_available):
                skipped += 1
                continue
        if case.category == "B" and args.live and live_available and case.mock_setup is None:
            # Run live (no mock)
            pass  # will be handled by run_case (mock_setup=None)

        stdout, stderr, exit_code = run_case(case, runner)
        md = case_to_markdown(case, stdout, stderr, exit_code)
        gk = _group_key(case.output_file)
        groups[gk].append(md)

    # ── Write Markdown docs ────────────────────────────────────────────
    docs_base = _PROJECT_ROOT / "docs" / "evidence"
    docs_base.mkdir(parents=True, exist_ok=True)

    # Create subdirs
    for subdir in ("cli", "cli/config", "cli/template", "cli/mcp"):
        (docs_base / subdir).mkdir(parents=True, exist_ok=True)

    files_written = 0
    for gk, md_blocks in sorted(groups.items()):
        subdir = _DOC_SUBDIR_MAP.get(gk, "cli")
        fname = f"{gk}.md"
        out_path = docs_base / subdir / fname

        title = gk.replace("-", " ").title()
        content = _GENERATED_HEADER
        content += f"# CLI Evidence: {title}\n\n"
        content += "\n".join(md_blocks)

        out_path.write_text(content)
        files_written += 1
        print(f"  wrote {out_path.relative_to(_PROJECT_ROOT)}")

    # ── README.md ──────────────────────────────────────────────────────
    readme = docs_base / "README.md"
    readme_content = _GENERATED_HEADER
    readme_content += "# CLI Evidence Documentation\n\n"
    readme_content += (
        "This directory contains auto-generated evidence of every CLI command's\n"
        "input→output behaviour. Each Markdown file shows the exact command invoked,\n"
        "its stdout, exit code, and stderr (when non-empty).\n\n"
    )
    readme_content += "## Regenerate\n\n"
    readme_content += "```bash\n"
    readme_content += "# Offline (mocked backend) — default\n"
    readme_content += "python scripts/capture_cli_evidence.py\n\n"
    readme_content += "# With real backend (requires E2B_API_KEY)\n"
    readme_content += "E2B_API_KEY=your-key python scripts/capture_cli_evidence.py --live\n\n"
    readme_content += "# Single command group\n"
    readme_content += "python scripts/capture_cli_evidence.py --command create\n"
    readme_content += "```\n\n"
    readme_content += "## Files\n\n"
    for gk in sorted(groups.keys()):
        subdir = _DOC_SUBDIR_MAP.get(gk, "cli")
        readme_content += f"- [`{subdir}/{gk}.md`]({subdir}/{gk}.md)\n"
    readme_content += f"\n**Total cases:** {total - skipped} run, {skipped} skipped\n"
    readme.write_text(readme_content)
    files_written += 1
    print(f"  wrote {readme.relative_to(_PROJECT_ROOT)}")

    print(f"\nDone: {total - skipped} cases run, {skipped} skipped, {files_written} files written.")


if __name__ == "__main__":
    main()
