"""Built-in template scaffolds for ``ebx template init``.

Provides pre-defined template cases (python, node, minimal) that generate
a complete set of files for a new sandbox template project.  Template strings
are embedded directly — examples/ is NOT read at runtime because it is not
packaged in the wheel.
"""

from __future__ import annotations

__all__ = [
    "available_cases",
    "render_scaffold",
]

# ---------------------------------------------------------------------------
# Case definitions: (name, description)
# ---------------------------------------------------------------------------

_CASES: list[tuple[str, str]] = [
    ("python", "Python 3.11 sandbox with shell, files, and code capabilities"),
    ("node", "Node.js 20 sandbox with shell, files, and code capabilities"),
    ("minimal", "Minimal template with template.yaml, Dockerfile, and README"),
]

# ---------------------------------------------------------------------------
# Template strings
# ---------------------------------------------------------------------------

_PYTHON_TEMPLATE_YAML = """\
name: {name}
version: "1.0.0"
description: "Python sandbox template"

base: python:3.11-slim

capabilities:
  - shell
  - files
  - code

resources:
  cpu: 2
  memory: 2048
"""

_PYTHON_DOCKERFILE = """\
FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive

# Install easy-sandbox SDK.
# When building locally via `ebx template deploy`, the SDK wheel
# is automatically injected into the build context as .whl file.
COPY *.whl /tmp/
RUN if ls /tmp/*.whl 1>/dev/null 2>&1; then \\
        pip install --no-cache-dir /tmp/*.whl && rm -f /tmp/*.whl; \\
    else \\
        pip install --no-cache-dir easy-sandbox; \\
    fi

WORKDIR /app
COPY commands.py .

EXPOSE 9000
CMD ["python3", "commands.py"]
"""

_PYTHON_COMMANDS = """\
\"\"\"Custom commands for {name}.\"\"\"
from __future__ import annotations

from easy_sandbox.server import (
    CapabilityGroup,
    CommandRegistry,
    SandboxServer,
    default_table,
)

table = default_table()
table.enable_group(CapabilityGroup.FILE_OPS)
table.enable_group(CapabilityGroup.PROCESS)
table.enable_group(CapabilityGroup.SYSTEM)

registry = CommandRegistry()


@registry.command("hello", description="Say hello.")
def hello(name: str = "World") -> str:
    return f"Hello, {{name}}!"


registry.freeze()
server = SandboxServer(registry=registry)
server.serve(port=9000)
"""

_PYTHON_README = """\
# {name}

A Python sandbox template generated by `ebx template init`.

## Quick Start

```bash
# Build and deploy to the cloud
ebx template deploy . --acr-namespace <your-namespace>

# Or install into local cache first
ebx install .
```
"""

# ---- Node ----

_NODE_TEMPLATE_YAML = """\
name: {name}
version: "1.0.0"
description: "Node.js sandbox template"

base: node:20-slim

capabilities:
  - shell
  - files
  - code

resources:
  cpu: 1
  memory: 2048
"""

_NODE_DOCKERFILE = """\
FROM node:20-slim

ENV DEBIAN_FRONTEND=noninteractive

# Install Python and easy-sandbox for the command server
RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip \\
    && rm -rf /var/lib/apt/lists/*
COPY *.whl /tmp/
RUN if ls /tmp/*.whl 1>/dev/null 2>&1; then \\
        pip3 install --no-cache-dir --break-system-packages /tmp/*.whl && rm -f /tmp/*.whl; \\
    else \\
        pip3 install --no-cache-dir --break-system-packages easy-sandbox; \\
    fi

WORKDIR /app
COPY commands.py .

EXPOSE 9000
CMD ["python3", "commands.py"]
"""

_NODE_COMMANDS = """\
\"\"\"Custom commands for {name}.\"\"\"\n\
from __future__ import annotations

from easy_sandbox.server import (
    CapabilityGroup,
    CommandRegistry,
    SandboxServer,
    default_table,
)

table = default_table()
table.enable_group(CapabilityGroup.FILE_OPS)
table.enable_group(CapabilityGroup.PROCESS)
table.enable_group(CapabilityGroup.SYSTEM)

registry = CommandRegistry()


@registry.command("hello", description="Say hello.")
def hello(name: str = "World") -> str:
    return f"Hello, {{name}}!"


registry.freeze()
server = SandboxServer(registry=registry)
server.serve(port=9000)
"""

_NODE_README = """\
# {name}

A Node.js sandbox template generated by `ebx template init`.

## Quick Start

```bash
# Build and deploy to the cloud
ebx template deploy . --acr-namespace <your-namespace>

# Or install into local cache first
ebx install .
```
"""

# ---- Minimal ----

_MINIMAL_TEMPLATE_YAML = """\
name: {name}
version: "1.0.0"
description: "Minimal sandbox template"

base: python:3.11-slim

capabilities:
  - shell
  - files
  - code
"""

_MINIMAL_DOCKERFILE = """\
FROM python:3.11-slim

COPY *.whl /tmp/
RUN if ls /tmp/*.whl 1>/dev/null 2>&1; then \\
        pip install --no-cache-dir /tmp/*.whl && rm -f /tmp/*.whl; \\
    else \\
        pip install --no-cache-dir easy-sandbox; \\
    fi

WORKDIR /app
"""

_MINIMAL_README = """\
# {name}

A minimal sandbox template generated by `ebx template init`.

## Quick Start

```bash
ebx template deploy . --acr-namespace <your-namespace>
```
"""

# ---------------------------------------------------------------------------
# Case → file mapping
# ---------------------------------------------------------------------------

_CASE_FILES: dict[str, dict[str, str]] = {
    "python": {
        "template.yaml": _PYTHON_TEMPLATE_YAML,
        "Dockerfile": _PYTHON_DOCKERFILE,
        "commands.py": _PYTHON_COMMANDS,
        "README.md": _PYTHON_README,
    },
    "node": {
        "template.yaml": _NODE_TEMPLATE_YAML,
        "Dockerfile": _NODE_DOCKERFILE,
        "commands.py": _NODE_COMMANDS,
        "README.md": _NODE_README,
    },
    "minimal": {
        "template.yaml": _MINIMAL_TEMPLATE_YAML,
        "Dockerfile": _MINIMAL_DOCKERFILE,
        "README.md": _MINIMAL_README,
    },
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def available_cases() -> list[tuple[str, str]]:
    """Return a list of ``(case_name, short_description)`` for built-in scaffolds."""
    return list(_CASES)


def render_scaffold(case: str, name: str) -> dict[str, str]:
    """Render a scaffold case, substituting *name* into templates.

    Args:
        case: One of the built-in case names (``python``, ``node``, ``minimal``).
        name: Template name to substitute into ``template.yaml`` and other files.

    Returns:
        A dict mapping relative file names to their rendered content.

    Raises:
        ValueError: If *case* is not a recognised scaffold name.
    """
    templates = _CASE_FILES.get(case)
    if templates is None:
        valid = ", ".join(c[0] for c in _CASES)
        raise ValueError(f"Unknown scaffold case '{case}'. Valid cases: {valid}")
    # Sanitize name to prevent ValueError from stray braces
    safe_name = str(name).replace("{", "").replace("}", "")
    return {filename: content.format(name=safe_name) for filename, content in templates.items()}
